version: '3.8'

services:

  db:
    container_name: film_library_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: film_library
    ports:
      - "5432:5432"
