// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ActorMovieDeleter is an autogenerated mock type for the ActorMovieDeleter type
type ActorMovieDeleter struct {
	mock.Mock
}

// DeleteActorMovie provides a mock function with given fields: movieId, actorsIds
func (_m *ActorMovieDeleter) DeleteActorMovie(movieId int, actorsIds []int) error {
	ret := _m.Called(movieId, actorsIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActorMovie")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []int) error); ok {
		r0 = rf(movieId, actorsIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewActorMovieDeleter creates a new instance of ActorMovieDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorMovieDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorMovieDeleter {
	mock := &ActorMovieDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
