// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	postgres "film_library/internal/storage/postgres"

	mock "github.com/stretchr/testify/mock"
)

// ActorsAllGetter is an autogenerated mock type for the ActorsAllGetter type
type ActorsAllGetter struct {
	mock.Mock
}

// GetActors provides a mock function with given fields:
func (_m *ActorsAllGetter) GetActors() ([]postgres.Actor, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActors")
	}

	var r0 []postgres.Actor
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]postgres.Actor, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []postgres.Actor); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.Actor)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActorsAllGetter creates a new instance of ActorsAllGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorsAllGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorsAllGetter {
	mock := &ActorsAllGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
