// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	postgres "film_library/internal/storage/postgres"

	mock "github.com/stretchr/testify/mock"
)

// MovieSearcherById is an autogenerated mock type for the MovieSearcherById type
type MovieSearcherById struct {
	mock.Mock
}

// GetMovie provides a mock function with given fields: movieId
func (_m *MovieSearcherById) GetMovie(movieId int) (postgres.Movie, error) {
	ret := _m.Called(movieId)

	if len(ret) == 0 {
		panic("no return value specified for GetMovie")
	}

	var r0 postgres.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (postgres.Movie, error)); ok {
		return rf(movieId)
	}
	if rf, ok := ret.Get(0).(func(int) postgres.Movie); ok {
		r0 = rf(movieId)
	} else {
		r0 = ret.Get(0).(postgres.Movie)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(movieId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMovieSearcherById creates a new instance of MovieSearcherById. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieSearcherById(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieSearcherById {
	mock := &MovieSearcherById{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
