env: "local" # local, dev, prod
storage: "postgres://root:root@localhost:5432/film_library"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  jwt_secret: "AuthorNikitaZhirnov"