package main

import (
	_ "film_library/docs" // docs is generated by Swag CLI, you have to import it.
	"film_library/internal/config"
	deleteActorMovie "film_library/internal/http-server/handlers/actor-movie/delete"
	saveActorMovie "film_library/internal/http-server/handlers/actor-movie/save"
	allActors "film_library/internal/http-server/handlers/actor/all"
	deleteActor "film_library/internal/http-server/handlers/actor/delete"
	saveActor "film_library/internal/http-server/handlers/actor/save"
	searchActor "film_library/internal/http-server/handlers/actor/search"
	updateActor "film_library/internal/http-server/handlers/actor/update"
	allMovies "film_library/internal/http-server/handlers/movie/all"
	deleteMovie "film_library/internal/http-server/handlers/movie/delete"
	saveMovie "film_library/internal/http-server/handlers/movie/save"
	searchMovieById "film_library/internal/http-server/handlers/movie/search_by_id"
	searchMovieByPart "film_library/internal/http-server/handlers/movie/search_by_part"
	updateMovie "film_library/internal/http-server/handlers/movie/update"
	"film_library/internal/http-server/handlers/user/signin"
	"film_library/internal/http-server/handlers/user/signup"
	mwAdminAuthenticator "film_library/internal/http-server/middleware/admin_authenticator"
	mwLogger "film_library/internal/http-server/middleware/logger"
	"film_library/internal/lib/logger/sl"
	"film_library/internal/storage/postgres"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/jwtauth/v5"
	httpSwagger "github.com/swaggo/http-swagger"
	"log/slog"
	"net/http"
	"os"
)

const (
	envLocal = "local"
	envDev   = "dev"
	envProd  = "prod"
)

var tokenAuth *jwtauth.JWTAuth

//	@title			Film Library API
//	@version		1.0
//	@description	API for VK contest
//	@termsOfService	http://swagger.io/terms/

//	@contact.name	Nikita Zhirnov
//	@contact.url	https://t.me/belkindelcin
//	@contact.email	naklz9@mail.ru

func main() {
	cfg := config.MustLoad()

	log := setupLogger(cfg.Env)

	log.Info("starting film_library api", slog.String("env", cfg.Env))
	log.Debug("debug messages are enabled")

	storage, err := postgres.New(cfg.Storage)
	if err != nil {
		log.Error("failed to init storage", sl.Err(err))
		os.Exit(1)
	}

	router := chi.NewRouter()

	tokenAuth = jwtauth.New("HS256", []byte(cfg.HTTPServer.JWTSecret), nil)

	router.Use(middleware.RequestID)
	router.Use(mwLogger.New(log))
	router.Use(middleware.Recoverer)
	router.Use(middleware.URLFormat)

	router.Post("/signup", signup.New(log, storage))

	router.Post("/signin", signin.New(log, storage, cfg.HTTPServer.JWTSecret))

	router.Group(func(r chi.Router) {
		r.Use(jwtauth.Verifier(tokenAuth))
		r.Use(mwAdminAuthenticator.New(tokenAuth, storage))

		r.Post("/actor/save", saveActor.New(log, storage))
		r.Post("/movie/save", saveMovie.New(log, storage))
		r.Post("/actor/update", updateActor.New(log, storage))
		r.Post("/movie/update", updateMovie.New(log, storage))
		r.Post("/actor-movie/save", saveActorMovie.New(log, storage))
		r.Delete("/actor/delete", deleteActor.New(log, storage))
		r.Delete("/movie/delete", deleteMovie.New(log, storage))
		r.Delete("/actor-movie/delete", deleteActorMovie.New(log, storage))
	})

	router.Group(func(r chi.Router) {
		r.Use(jwtauth.Verifier(tokenAuth))
		r.Use(jwtauth.Authenticator(tokenAuth))

		r.Get("/actor/search", searchActor.New(log, storage))
		r.Get("/movie/search_by_id", searchMovieById.New(log, storage))
		r.Get("/movie/all", allMovies.New(log, storage))
		r.Get("/actor/all", allActors.New(log, storage))
		r.Get("/movie/search_by_part", searchMovieByPart.New(log, storage))
	})

	router.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8082/swagger/doc.json"), //The url pointing to API definition
	))

	log.Info("starting http server", slog.String("address", cfg.HTTPServer.Address))
	srv := &http.Server{
		Addr:         cfg.HTTPServer.Address,
		Handler:      router,
		ReadTimeout:  cfg.HTTPServer.Timeout,
		WriteTimeout: cfg.HTTPServer.Timeout,
		IdleTimeout:  cfg.HTTPServer.IdleTimeout,
	}

	if err := srv.ListenAndServe(); err != nil {
		log.Error("failed to start http server", sl.Err(err))
	}

	log.Error("http server stopped")
}

func setupLogger(env string) *slog.Logger {
	var log *slog.Logger

	switch env {
	case envLocal:
		log = slog.New(
			slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}),
		)
	case envDev:
		log = slog.New(
			slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelDebug}),
		)
	case envProd:
		log = slog.New(
			slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}),
		)
	}

	return log
}
