// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MovieSaver is an autogenerated mock type for the MovieSaver type
type MovieSaver struct {
	mock.Mock
}

// SaveMovie provides a mock function with given fields: title, description, releaseDate, rating, actorsIds
func (_m *MovieSaver) SaveMovie(title string, description string, releaseDate string, rating int, actorsIds []int) (int, error) {
	ret := _m.Called(title, description, releaseDate, rating, actorsIds)

	if len(ret) == 0 {
		panic("no return value specified for SaveMovie")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, int, []int) (int, error)); ok {
		return rf(title, description, releaseDate, rating, actorsIds)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, int, []int) int); ok {
		r0 = rf(title, description, releaseDate, rating, actorsIds)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, int, []int) error); ok {
		r1 = rf(title, description, releaseDate, rating, actorsIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMovieSaver creates a new instance of MovieSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieSaver {
	mock := &MovieSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
