// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	postgres "film_library/internal/storage/postgres"

	mock "github.com/stretchr/testify/mock"
)

// ActorSearcher is an autogenerated mock type for the ActorSearcher type
type ActorSearcher struct {
	mock.Mock
}

// GetActor provides a mock function with given fields: actorId
func (_m *ActorSearcher) GetActor(actorId int) (postgres.Actor, error) {
	ret := _m.Called(actorId)

	if len(ret) == 0 {
		panic("no return value specified for GetActor")
	}

	var r0 postgres.Actor
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (postgres.Actor, error)); ok {
		return rf(actorId)
	}
	if rf, ok := ret.Get(0).(func(int) postgres.Actor); ok {
		r0 = rf(actorId)
	} else {
		r0 = ret.Get(0).(postgres.Actor)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(actorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewActorSearcher creates a new instance of ActorSearcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActorSearcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActorSearcher {
	mock := &ActorSearcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
